### ISSUE TITLE
Error on Android 5.1

### ISSUE THREAD

**Issue by dapearce** [Glitchbone/CordovaYoutubeVideoPlayer#10]
Hi, this is working on older versions of android but getting a "Can't play this video." error when trying to use it in Android 5.1. Any idea what's going on?

**Comment by cdarken** [comment]
Yeah, same for me.

**Comment by mparpaillon** [comment]
Idem

**Comment by matteodesanti** [comment]
Same, sadly

**Comment by JerryBels** [comment]
+1

**Comment by hryamzik** [comment]
The workaround is to check device type and version:

```js
  $scope.fallBackToUrl = function()
  {
    version = ionic.Platform.version();
    if (ionic.Platform.isAndroid() && ( version >= 5 || version === 0 )) {
      return true;
    }
    return false;
  }
```

And use ng-if:
```html
<ion-item ng-if="fallBackToUrl()"
```

**Comment by JerryBels** [comment]
@hryamzik thanks, but what to do when the version is wrong ? I can't let the app do anything :/

**Comment by hryamzik** [comment]
@JerryBels
```js
    <div class="video-container">
      <iframe ng-src="{{getIframeSrc(video.snippet.resourceId.videoId)}}" frameborder="0" allowfullscreen></iframe>
    </div>
```

```css
.video-container {
    position: relative;
    padding-bottom: 56.25%;
    padding-top: 30px; height: 0; overflow: hidden;
}

.video-container iframe, .video-container object, .video-container embed {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}
```

```js
.controller('VideoDetailCtrl', function($scope, $stateParams, $sce, YouTubeService) {
<...>
  $scope.getIframeSrc = function (videoId) {
    return $sce.trustAsResourceUrl('http://www.youtube.com/embed/' + videoId + '?autoplay=1');
  };

})
